// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeTTsAIrWHaaC0W8ddBVzUtbvOUbiE0DQ',
    appId: '1:117453627407:android:46bdd171e237cef08c837a',
    messagingSenderId: '117453627407',
    projectId: 'event-app-a2',
    storageBucket: 'event-app-a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbkzLDVvOztByk84_VGUnKe4UP6BOaDl8',
    appId: '1:117453627407:ios:67d365c5b58430c88c837a',
    messagingSenderId: '117453627407',
    projectId: 'event-app-a2',
    storageBucket: 'event-app-a2.firebasestorage.app',
    androidClientId: '117453627407-t38a71j05ou0a6bq0dkskg1ostnmapbf.apps.googleusercontent.com',
    iosClientId: '117453627407-31c7gnlt85vghqbev2fptf7cljigpr4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIWblJPXZigpidj15DrSXYDH7XVn1bdxw',
    appId: '1:117453627407:web:b650067f9f9206ce8c837a',
    messagingSenderId: '117453627407',
    projectId: 'event-app-a2',
    authDomain: 'event-app-a2.firebaseapp.com',
    storageBucket: 'event-app-a2.firebasestorage.app',
    measurementId: 'G-59QLXK4QQY',
  );

}